// app/layout.tsx
import React from 'react';
import { Paytone_One } from 'next/font/google'; // Importa la fuente desde next/font
import './globals.css'; // Importa el archivo CSS global
import { ThemeProvider } from '@/components/themeprovider';

// Configura la fuente con next/font
const paytoneOne = Paytone_One({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={paytoneOne.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
